name: Create Pull request

on: [push]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ["de-german", "fa-persian"]
    steps:
      - name: Fetch translation repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: solidity-docs-test/${{ matrix.repos }}

      - name: debug step # TODO: remove it
        run: |
          pwd
          ls -altrh

      - name: Fetch solidity repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ethereum/solidity
          path: solidity

      - name: Merge repositories
        run: |
          cp -r solidity/docs/* .
          rm -rf solidity

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: Solidity-PR-Bot <piahoo+github.bot@gmail.com>
          author: Solidity-PR-Bot <piahoo+github.bot@gmail.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: "Sync with solidity/docs/"
          body: |
            This PR was automatically generated.
            Merge changes from [solidity][1]/docs @ {{ here will be link to commit }}

            Please fix the conflicts by pushing new commits to this pull request, either by editing the files directly on GitHub or by checking out this branch.

            - [ ]  changed file 1
            - [ ]  changed file 2
            - [ ]  changed file 3


            [1]: https://github.com/ethereum/solidity

          labels: |
            report
            automated pr
          assignees: Solidity-PR-Bot
          reviewers: o-lenczyk
          team-reviewers: |
            o-lenczyk
          draft: false
