name: Create Pull request

on: [push]

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ["de-german"]
    steps:
      - name: Fetch first repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: solidity-docs-test/${{ matrix.repos }}

      - name: debug step
        run: |
          pwd
          ls -altrh

      - name: Fetch second repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ethereum/solidity
          path: solidity

      - name: debug step2
        run: |
          pwd
          ls -altrh
          cp -r solidity/docs/* .
          rm -rf solidity
          ls -altrh

      - name: Make changes to pull request
        run: |
          date +%s > report.txt
          pwd
          ls -altrh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: Solidity-PR-Bot <piahoo+github.bot@gmail.com>
          author: Solidity-PR-Bot <piahoo+github.bot@gmail.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: "[Example] Update report"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: Solidity-PR-Bot
          reviewers: Solidity-PR-Bot
          team-reviewers: |
            o-lenczyk
          draft: false
